export const newtworkCollections = {
  "FB_Mnet": "Facebook_Mnet_Daily",
  "FB_MnetBing": "Facebook_MnetBing_Daily",
  "FB_Enki": "Facebook_Enki",
  "FB_System1": 'Facebook_System1',
  "FB_Rsoc": 'Facebook_Rsoc',
  "FB_Tonic": 'Facebook_Tonic',
  "FB_DomainActive": "Facebook_DActive_Names",
  "FB_Bodies": "Facebook_Bodies",
  "FB_Bodies1": "Facebook_Bodies1",
  "Newsbreak_DA": "Newsbreak_DomainActive",
  "FB_Tonic1": "Facebook_Tonic1",
  "FB_Sedo": "Facebook_Sedo",
  "FB_Inmobi": "Facebook_Inmobi",
  "FB_TonicRsoc": "Facebook_TonicRsoc",
  "FB_InuvoPrism": "Facebook_InuvoPrismDaily",
  "FB_CodeFuel": "Facebook_CodeFuel_Daily",
  "FB_Predicto": 'Facebook_Predicto_Daily',
  "FB_Affinity": "Facebook_Affinity_Daily",
  "FB_Botup": "Facebook_Botup_Daily",
  "FB_MWG": "Facebook_Mwg_Daily",
  "Taboola_Inuvoprism": "Taboola_InuvoPrismDaily"
}
export const newtworkCollectionsAdsets = {
  "FB_Mnet": "Facebook_Mnet_Daily",
  "FB_MnetBing": "Facebook_MnetBing_Daily",
  "FB_Enki": "Facebook_Enki",
  "FB_System1": 'Facebook_System1',
  "FB_Rsoc": 'Facebook_Rsoc',
  "FB_Tonic": 'Facebook_Tonic',
  "FB_DomainActive": "Facebook_DActive_Names",
  "FB_Bodies": "Facebook_Bodies",
  "FB_Bodies1": "Facebook_Bodies1",
  "Newsbreak_DA": "Newsbreak_DomainActive",
  "FB_Tonic1": "Facebook_Tonic1",
  "FB_Sedo": "Facebook_Sedo",
  "FB_Inmobi": "Facebook_Inmobi",
  "FB_TonicRsoc": "Facebook_TonicRsoc",
  "FB_InuvoPrism": "Facebook_InuvoPrismDaily",
  "FB_CodeFuel": "Facebook_CodeFuel_Daily",
  "FB_Predicto": 'Facebook_Mnet_AD',
  "FB_Affinity": "Facebook_Mnet_AD",
  "FB_Botup": "Facebook_Mnet_AD",
  "FB_MWG": "Facebook_Mwg_Daily",
  "Taboola_Inuvoprism": "Taboola_InuvoPrismDaily"
}
export const newtworkCollectionsForAds = {
  "FB_Mnet": "Facebook_AD_Daily",
  "FB_MnetBing": "Facebook_AD_Daily",
  "FB_Enki": "Facebook_Mnet_AD",
  "FB_System1": 'Facebook_Mnet_AD',
  "FB_Rsoc": 'Facebook_Mnet_AD',
  "FB_Tonic": 'Facebook_Mnet_AD',
  "FB_DomainActive": "Facebook_Mnet_AD",
  "FB_Bodies": "Facebook_Mnet_AD",
  "FB_Bodies1": "Facebook_Mnet_AD",
  "Newsbreak_DA": "Facebook_Mnet_AD",
  "FB_Tonic1": "Facebook_Mnet_AD",
  "FB_Sedo": "Facebook_Mnet_AD",
  "FB_Inmobi": "Facebook_Mnet_AD",
  "FB_TonicRsoc": "Facebook_Mnet_AD",
  "FB_InuvoPrism": "Facebook_Mnet_AD",
  "FB_CodeFuel": "Facebook_AD_Daily",
  "FB_Predicto": 'Facebook_Mnet_AD',
  "FB_Affinity": "Facebook_AD_Daily",
  "FB_Botup": "Facebook_AD_Daily",
  "FB_MWG": "Facebook_AD_Daily",
  "FB_Media": "Facebook_AD_Daily",
  "Taboola_Inuvoprism": "Facebook_Mnet_AD"
}
export const selectTimezone = {
    UTC: 'UTCDate',
    EEST: 'EESTDate',
    EDT: 'EDTDate',
    CST: 'CSTDate',
    PDT: 'PDTDate',
    IST: 'ISTDate',
    BST: 'BSTDate',
    GMT: 'GMTDate',
    MST: 'MSTDate',
    CDT: 'CDTDate',
    AST: 'ASTDate',
    DST: 'DSTDate',
    CEST: 'CESTDate'
};