import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import "../styles/global.css";
import "../styles/reportshistory.css"
// import "@/lib/agGridSetup";
import { AntdRegistry } from '@ant-design/nextjs-registry';

import SessionProviderWrapper from "../layouts/SessionProvider/session"
// import AuthGuard from "../layouts/AuthLayout/AuthGuard"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <link rel="icon" type="image/png" href="/ssk1.png" />

      </head>
      <body className="min-h-full flex flex-col">
        {/* <SessionProviderWrapper> */}
        {/* <AuthGuard /> */}
        {/* {children} */}
        <AntdRegistry>
          {children}
        </AntdRegistry>
        {/* </SessionProviderWrapper> */}
      </body>
    </html>
  );
}
