export const TIMEZONES = [
    "UTC",
    "EEST",
    "CEST",
    "EDT",
    "CST",
    "PDT",
    "IST",
    "BST",
    "GMT",
    "MST",
    "CDT",
    "AST",
    "DST",
    "HST",
    "EST",
];

export const TIMEZONE_FULL_NAMES = {
    EDT: "America/New_York",
    UTC: "Atlantic/Azores",
    EEST: "Europe/Athens",
    CEST: "Europe/Paris",
    CST: "America/Mexico_City",
    PDT: "America/Los_Angeles",
    BST: "Europe/London",
    GMT: "Africa/Accra",
    IST: "Asia/Kolkata",
    MST: "America/Dawson",
    CDT: "America/Chicago",
    AST: "America/Puerto_Rico",
    DST: "Asia/Dubai",
    HST: "Pacific/Honolulu",
    EST: "America/Toronto",
};

export const TIMEZONE_SHORT_NAMES = {
    "America/New_York": "EDT",
    "Atlantic/Azores": "UTC",
    "Europe/Athens": "EEST",
    "Europe/Paris": "CEST",
    "America/Mexico_City": "CST",
    "America/Los_Angeles": "PDT",
    "Europe/London": "BST",
    "Africa/Accra": "GMT",
    "Asia/Kolkata": "IST",
    "America/Dawson": "MST",
    "America/Chicago": "CDT",
    "America/Puerto_Rico": "AST",
    "Asia/Dubai": "DST",
    "Pacific/Honolulu": "HST",
    "America/Toronto": "EST",
};